# Generated by Django 4.1.5 on 2023-01-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='nickname',
            new_name='nick_name',
        ),
    ]
