# Generated by Django 4.1.5 on 2023-01-22 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_firstname_usersmodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
