# Generated by Django 4.1.5 on 2023-01-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
