# Generated by Django 4.1.5 on 2023-01-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersmodel_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
