# Generated by Django 4.1.6 on 2023-02-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
        ('labels', '0001_initial'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='creator',
                to='users.users'
            ),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='executor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='executor',
                to='users.users'
            ),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='labels',
            field=models.ManyToManyField(
                through='tasks.TaskLabelModel',
                to='labels.labelmodel'
            ),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='statuses.statusmodel'
            ),
        ),
        migrations.AddField(
            model_name='tasklabelmodel',
            name='label',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='labels.labelmodel'
            ),
        ),
        migrations.AddField(
            model_name='tasklabelmodel',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='tasks.tasksmodel'
            ),
        ),
    ]
